/**
 * Copyright (C) 2020 Massimiliano Ghilardi
 *
 * This file is part of m64th.
 *
 * m64th is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation, either version 3
 * of the License, or (at your option) any later version.
 *
 * m64th is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with m64th.  If not, see <https://www.gnu.org/licenses/>.
 */

#include "impl.h"
#include "include/dict_fwd.h"       /* m6dict_... */
#include "include/hashmap_number.h" /* m6dict_... */
#include "include/m64th.h"
#include "include/opt_rules.mh" /* OPT*_RULES */
#include "include/word_fwd.h"   /* m6w_...    */

#include <assert.h>
#include <stdio.h>
#include <string.h>

#define N_OF(array) (sizeof(array) / sizeof((array)[0]))

const char license[] = "/**\n\
 * Copyright (C) 2020 Massimiliano Ghilardi\n\
 *\n\
 * This file is part of m64th.\n\
 *\n\
 * m64th is free software: you can redistribute it and/or modify\n\
 * it under the terms of the GNU Lesser General Public License\n\
 * as published by the Free Software Foundation, either version 3\n\
 * of the License, or (at your option) any later version.\n\
 *\n\
 * m64th is distributed in the hope that it will be useful,\n\
 * but WITHOUT ANY WARRANTY; without even the implied warranty of\n\
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n\
 * GNU Lesser General Public License for more details.\n\
 *\n\
 * You should have received a copy of the GNU Lesser General Public License\n\
 * along with m64th.  If not, see <https://www.gnu.org/licenses/>.\n\
 */\n\n\
\n\
/**\n\
 * For the curious: this output has the same copyright and license\n\
 * as the program m64th, because it's an extract of m64th sources.\n\
 */\n\n";

#define N_OF(array) (sizeof(array) / sizeof((array)[0]))

#define OPT1_TO_TOKENS(...)                                                                        \
    {WRAP_ARGS(M6TOKEN_SYM_COMMA, T(COUNT_ARGS(__VA_ARGS__) - 1),                                  \
               FIRST_3_ARGS(__VA_ARGS__, _missing_, _missing_))},
#define OPT2_TO_TOKENS(...)                                                                        \
    {WRAP_ARGS(M6TOKEN_SYM_COMMA, T(COUNT_ARGS(__VA_ARGS__) - 2),                                  \
               FIRST_5_ARGS(__VA_ARGS__, _missing_, _missing_, _missing_))},
#define OPT3_TO_TOKENS(...)                                                                        \
    {WRAP_ARGS(M6TOKEN_SYM_COMMA, T(COUNT_ARGS(__VA_ARGS__) - 3),                                  \
               FIRST_5_ARGS(__VA_ARGS__, _missing_, _missing_))},

static void genopt_print_n_tokens(m6ucell x, unsigned n, unsigned index, FILE *out);

static void genopt_print_1_token(m6token tok, unsigned index, FILE *out) {
    const m6string s = m6word_ident(m6token_to_word(tok));
    if (s.addr && s.n) {
        fputs(&"|(M6"[index ? 0 : 2], out);
        m6string_print(s, m6mode_user, out);
        if (index) {
            fprintf(out, "<<%u)", index * 16);
        }
    } else if (tok) {
        if (index) {
            fprintf(out, "|(%u<<%u)", (unsigned)tok, index * 16);
        } else {
            fprintf(out, "%u", (unsigned)tok);
        }
    }
}

static void genopt_print_counted_tokens(m6ucell x, FILE *out) {
    unsigned count = (unsigned)(m6token)x;
    fprintf(out, "%u", count);
    genopt_print_n_tokens(x >> 16, count, 1, out);
}

static void genopt_print_n_tokens(m6ucell x, unsigned n, unsigned index, FILE *out) {
    unsigned i;
    for (i = 0; i < n; i++) {
        genopt_print_1_token((m6token)x, index++, out);
        x >>= 16;
    }
}

static void genopt2_dump(const m6hashmap_int *map, const char *label, FILE *out) {
    m6ucell i, cap = 2u << map->lcap;
    fprintf(out,
            "/*\n"
            " * DO NOT EDIT! this file was autogenerated with command './gen'\n"
            " * any change will be lost when the command is run again.\n"
            " */\n"
            "/* clang-format off */\n"
            "#define %s_HASHMAP(start, entry)\t\\\n"
            "start(/*size*/ %u, /*lcap*/ %u)\t\\\n",
            label, (unsigned)map->size, (unsigned)map->lcap);
    for (i = 0; i < cap; i++) {
        const m6hashmap_entry_int *e = map->vec + i;
        fputs("entry(", out);
        if (e->next == m6hash_no_entry_int) {
            fputs("0,\t0", out);
        } else {
            genopt_print_n_tokens(e->key, 2, 0, out);
            fputs(",\t", out);
            genopt_print_counted_tokens(e->val, out);
        }
        fprintf(out, ",\t%d)%s\n", (int)e->next, (i + 1 == cap ? "" : "\t\\"));
    }
}

static void genopt3_dump(const m6hashmap_cell *map, const char *label, FILE *out) {
    m6ucell i, cap = 2u << map->lcap;
    fprintf(out,
            "/*\n"
            " * DO NOT EDIT! this file was autogenerated with command './gen'\n"
            " * any change will be lost when the command is run again.\n"
            " */\n"
            "/* clang-format off */\n"
            "#define %s_HASHMAP(start, entry)\t\\\n"
            "start(/*size*/ %u, /*lcap*/ %u)\t\\\n",
            label, (unsigned)map->size, (unsigned)map->lcap);
    for (i = 0; i < cap; i++) {
        const m6hashmap_entry_cell *e = map->vec + i;
        fputs("entry(", out);
        if (e->next == m6hash_no_entry_cell) {
            fputs("0,\t0", out);
        } else {
            genopt_print_n_tokens(e->key, 3, 0, out);
            fputs(",\t", out);
            genopt_print_counted_tokens(e->val, out);
        }
        fprintf(out, ",\t%d)%s\n", (int)e->next, (i + 1 == cap ? "" : "\t\\"));
    }
}

static void genopt2_add(m6hashmap_int *map, const m6token opt[6]) {
    m6cell key = opt[1] | ((m6cell)opt[2] << 16);
    m6cell val = opt[0] | ((m6cell)opt[3] << 16) | ((m6cell)opt[4] << 32) | ((m6cell)opt[5] << 48);
    const m6hashmap_entry_int *e;
    assert(opt[0] <= 3);
    e = m6hashmap_find_int(map, key);
    assert(e == NULL);
    e = m6hashmap_insert_int(map, key, val);
    assert(e != NULL);
}

static void genopt3_add(m6hashmap_cell *map, const m6token opt[6]) {
    m6cell key = opt[1] | ((m6cell)opt[2] << 16) | ((m6cell)opt[3] << 32);
    m6cell val = opt[0] | ((m6cell)opt[4] << 16) | ((m6cell)opt[5] << 32);
    const m6hashmap_entry_cell *e;
    assert(opt[0] <= 2);
    e = m6hashmap_find_cell(map, key);
    assert(e == NULL);
    e = m6hashmap_insert_cell(map, key, val);
    assert(e != NULL);
}

static void genopt2_run(FILE *out) {
    static const m6token opt[][6] = {OPT2_RULES(OPT2_TO_TOKENS)};
    m6hashmap_int *map = m6hashmap_new_int(N_OF(opt) / 2);
    m6cell i;
    for (i = 0; i < (m6cell)N_OF(opt); i++) {
        genopt2_add(map, opt[i]);
    }
    genopt2_dump(map, "OPT2", out);
}

static void genopt2_midprio_run(FILE *out) {
    static const m6token opt[][6] = {OPT2_RULES_MIDPRIO(OPT2_TO_TOKENS)};
    m6hashmap_int *map = m6hashmap_new_int(N_OF(opt) / 2);
    m6cell i;
    for (i = 0; i < (m6cell)N_OF(opt); i++) {
        genopt2_add(map, opt[i]);
    }
    genopt2_dump(map, "OPT2_MIDPRIO", out);
}

static void genopt3_run(FILE *out) {
    static const m6token opt[][6] = {OPT3_RULES(OPT3_TO_TOKENS)};
    m6hashmap_cell *map = m6hashmap_new_cell(N_OF(opt) / 4 * 3);
    m6cell i;
    for (i = 0; i < (m6cell)N_OF(opt); i++) {
        genopt3_add(map, opt[i]);
    }
    genopt3_dump(map, "OPT3", out);
}

static void genopt_to_file(const char *path, void (*gen)(FILE *out)) {
    FILE *f = fopen(path, "w");
    gen(f);
    fclose(f);
    fprintf(stdout, "# file '%s' updated\n", path);
}

static void run_show_words(m6printmode mode, FILE *out) {
    const m6dict *dict[] = {
        /* &m6dict_forth_root, */
        &m6dict_forth, &m6dict_m64th_user, &m6dict_m64th_c, &m6dict_m64th_core, &m6dict_m64th_impl,
    };
    m6cell i;
    fputs(license, stdout);
    for (i = 0; i < (m6cell)N_OF(dict); i++) {
        m6dict_print(dict[i], NULL, mode, out);
    }
}

static inline void dpush(m64th *m, m6cell x) {
    *--m->dstack.curr = x;
}

static void run_benchmark(FILE *out) {
    static const m6token code[] = {m6do,     m6two_dup,   m6crc_string, m6drop,
                                   m6_loop_, (m6token)-5, m6bye};
    m64th *m = m64th_new(m6opt_return_stack_is_c_stack);
#ifdef __x86_64__
    const double n = 1e9f;
#else
    const double n = 1e8f;
#endif
    fprintf(out, "benchmark: crc-string%s %g iterations... ",
            (m64th_cpu_features_enabled() & m64th_cpu_feature_crc32c ? "/simd" : ""), n);
    fflush(out);
    m->ip = code;
    dpush(m, (m6cell) "1234567890123456789012345678901234567890123456789012345678901234");
    dpush(m, 64);
    dpush(m, (m6cell)n);
    dpush(m, 0);
    m64th_run(m);
    m64th_del(m);
    fputs("done.\n", out);
}

int main(int argc, char *argv[]) {
    m6cell show_words = argc >= 2 && !strcmp(argv[1], "words");
    m6cell show_disasm = argc >= 2 && !strcmp(argv[1], "disasm");
    m6cell benchmark = argc >= 2 && !strcmp(argv[1], "bench");
    m6cell cpu_features_disable_mask = argc >= 3 && !strcmp(argv[2], "nosimd") ? ttrue : tfalse;
    m6cell cpu_features;

    m64th_init();
    m64th_cpu_features_disable(cpu_features_disable_mask);
    cpu_features = m64th_cpu_features_enabled();

    if (benchmark) {
#if defined(__x86_64__)
#define ARCH_STR_ "amd64 "
#elif defined(__aarch64__)
#define ARCH_STR_ "arm64 "
#else
#define ARCH_STR_ " "
#endif
        if (cpu_features == m64th_cpu_feature_cannot_detect) {
            fputs("# no support to detect optional CPU features on this " ARCH_STR_ "CPU/OS\n",
                  stdout);
        } else if (cpu_features & m64th_cpu_feature_crc32c) {
            fputs("# this " ARCH_STR_ "CPU has crc32c asm instructions\n", stdout);
        } else {
            fputs("# this " ARCH_STR_ "CPU does not have crc32c asm instructions\n", stdout);
        }
        run_benchmark(stdout);
    } else if (show_words || show_disasm) {
        run_show_words(show_words ? m6mode_user : m6mode_c_disasm, stdout);
    } else {
        genopt_to_file("include/opt2_hash.mh", genopt2_run);
        genopt_to_file("include/opt3_hash.mh", genopt3_run);
        genopt_to_file("include/opt2_midprio_hash.mh", genopt2_midprio_run);
    }
    return 0;
}
